#!/bin/bash

# replace these glyphs
sed --regexp-extended \
    --expression="

      # squeeze space bubbles
      s/[[:space:]]+/ /g

      # skip trailing space
      s/ $//

      # multiple types of 'minus'
      s/‐/-/g

      s/„([[:alpha:][:space:]])/\\\\glqq{}\1/g
      s/„/\\\\glqq/g

      s/“([[:alpha:][:space:]])/\\\\grqq{}\1/g
      s/“/\\\\grqq/g

    "
 
# signalize success
exit 0

